### ISSUE TITLE
500 errors for pages that are not generated during build

### ISSUE THREAD

**Issue by gijsbotje** [bestofjs/bestofjs#205]
In the new Next site I tried to open a featured project. This unfortunately resulted in a 500 error screen.
https://bestofjs.org/projects/blueprint
https://bestofjs.org/projects/recoil

i've been looking for a reason but haven't found it yet.

**Comment by michaelrambeau** [comment]
Thank you @gijsbotje for the report!

I can see this error message in the log and it happens for a lot of URLs:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /var/task/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:364:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:700:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at /var/task/node_modules/next/dist/server/require-hook.js:110:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at e.<computed>._module.Module._load (/var/task/___vc/__launcher.js:15:1964)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED',
  page: '/projects/pug'
}
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /var/task/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:364:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:700:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at /var/task/node_modules/next/dist/server/require-hook.js:110:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at e.<computed>._module.Module._load (/var/task/___vc/__launcher.js:15:1964)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED',
  page: '/projects/pug'
}
RequestId: 87a57e2e-7d69-4508-8111-68c8763fae79 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I cannot reproduce the error in local 🙀 

It's weird as nothing has changed during the last days... I may try to upgrade Next.js to the latest version. I'm investigating...

**Comment by michaelrambeau** [comment]
It seems that the upgrade to Next.js `13.5.2` fixed the issue.

@gijsbotje could you check again?

**Comment by gijsbotje** [comment]
@michaelrambeau yes that seems to have fixed it!

**Comment by zawarudo** [comment]
I've confirmed also, this is fixed 🎉
